# Dependencies
markdown:         kramdown
highlighter:      rouge


algolia:
   application_id: 600WCX6IGK
   index_name: moo99.github.io
   search_only_api_key: d738a7a4f549be6c1dd19ae9c6d1522e

# Plugins
plugins:
  - jekyll-archives

# Permalinks
permalink:        pretty
page_permalink:   pretty

# Setup
title:            moo99
tagline:
description:      無
url:              http://moo99.github.io
baseurl:          http://moo99.github.io/

author:
  name:           'Jack Kwon'
  url:            https://twitter.com/Kwonhyuckmin

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/moo99
