# Dependencies
markdown:         kramdown
highlighter:      rouge


algolia:
   application_id: 600WCX6IGK
   index_name: moo99.github.io
   search_only_api_key: d738a7a4f549be6c1dd19ae9c6d1522e


# Permalinks
permalink:        pretty
page_permalink:   pretty

# Setup
title:            The Drafts
tagline:
description:      just have to be written
url:              http://moo99.github.io
baseurl:          http://moo99.github.io/

author:
  name:           'moo99'
  url:            https://twitter.com/Kwonhyuckmin

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/moo99

# !! You don't need to change any of the configuration flags below !!
#

future: true

# The release of Jekyll Now that you're using
version: v3.0.2

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - org
