# Dependencies
markdown:         kramdown
highlighter:      rouge


algolia:
   application_id: 600WCX6IGK
   index_name: moo99.github.io
   search_only_api_key: d738a7a4f549be6c1dd19ae9c6d1522e

# Plugins
plugins:
  - jekyll-archives

# Permalinks
permalink:        pretty
page_permalink:   pretty

# Setup
title:            Index Cards
tagline:
description:      personal logs
url:              http://moo99.github.io
baseurl:          http://moo99.github.io/

author:
  name:           'moo99'
  url:            https://twitter.com/Kwonhyuckmin

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/moo99

# Archives
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
